---
timeout: 180
instances: 1
memory: 512M
env:
    SPRING_PROFILES_DEFAULT: cloud
    JAVA_OPTS: -Djava.security.egd=file:///dev/urandom
applications:
- name: iotCloudConfigServer
  path: cf-cloud-config-server/build/libs/cloud-config-0.1.jar
